version: "3"

services:
    client:
        image: vue-app 
        build: 
            context: ./client
            dockerfile: Dockerfile
        volumes: 
            - ../client:/app
        ports: 
            - 127.0.0.1:8082:80
        depends_on: 
            - server    

    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        image: dormhub-server
        restart: unless-stopped
        volumes: 
            - ./server:/usr/src/app
        ports: 
            - "127.0.0.1:8081:8081"
        networks: 
            - dormhub-app
        depends_on: 
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        networks: 
            - dormhub-app
        volumes: 
            - mongo-data:/data/db

networks: 
    dormhub-app:
        driver: bridge

volumes: 
    mongo-data:
        driver: local