packages:
  - client
  - server
overrides:
  "@cypress/request>qs": "^6.15.2"
  "@cypress/request>uuid": "^11.1.1"
allowBuilds:
  core-js: false
  cypress: true
  deasync: true
  ejs: false
  esbuild: true
  fsevents: true
  mongodb-memory-server: true
  sharp: true
  yorkie: false
